platform :ios, "8.0"
target 'LivingShow' do

pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 3.8.1'
pod 'BarrageRenderer', '~> 1.8.1'
#pod 'GPUImage', '~> 0.1.7'
pod 'LFLiveKit', '~> 1.9.0'

xcodeproj 'LivingShow.xcodeproj'

end
